class Config:
  OPENPIBO_PATH="/home/pi/openpibo"
  OPENPIBO_DATA_PATH="/home/pi/openpibo-data"
  TESTDATA_PATH =OPENPIBO_DATA_PATH+"/testdata"
  PROC_PATH =OPENPIBO_DATA_PATH+"/proc"
  MODEL_PATH=OPENPIBO_DATA_PATH+"/models"
  KAKAO_ACCOUNT="4a8d7d0801bb5757c3e1ce20de255408"
